
[[_extensions_timestamp]]
=== Timestamp Extension

The timestamp extension adds a `timestamp` to the message object for every message the client and/or server sends.
It is a non-standard extension because it does not add the additional fields to the `ext` field, but to the message object itself.
This extension requires both a client-side extension and a server-side extension.
The server-side extension is available in Java.

==== Enabling the Server-Side Extension

To enable support for time-stamped messages, you must add the extension to the `BayeuxServer` instance during initialization:

[source,java,indent=0]
----
include::{doc_code}/ExtensionsDocs.java[tags=timestamp]
----

==== Enabling the Client-Side Extension

`TimeStamp.js` provides the client-side extension implementation, and it is sufficient to import and register an instance with the CometD object:

[source,javascript]
----
import {TimeStampExtension} from "cometd/TimeStampExtension.js";

cometd.registerExtension("timestamp", new TimeStampExtension());
----

The example above is valid also when using the jQuery binding.
