
[[_extensions_binary]]
=== Binary Extension

The binary extension allows applications to send and receive messages containing binary data, and therefore to upload and download binary data such as files or images.
This extension requires both a client-side extension and a server-side extension.
The server-side extension is available in Java.

==== Enabling the Server-side Extension

To enable support for binary data in messages, you must add the extension to the `BayeuxServer` instance during initialization:

[source,java,indent=0]
----
include::{doc_code}/ExtensionsDocs.java[tags=binaryServer]
----

==== Enabling the Client-side Extension

`BinaryExtension.js` provides the client-side extension implementation, and it is sufficient to import and register an instance with the CometD object:

[source,ecmascript6]
----
import {BinaryExtension} from "cometd/BinaryExtension.js";

cometd.registerExtension("binary", new BinaryExtension());
----

The example above is valid also when using the jQuery binding.

For Java clients, you must add the extension to the `BayeuxClient` instance:

[source,java]
----
bayeuxClient.addExtension(new org.cometd.client.ext.BinaryExtension());
----
