
[[_javascript]]
== JavaScript Library

The CometD project provides a client-side JavaScript library to be used in browsers, as well as client-side and server-side JavaScript library to be used in NodeJS.

=== CometD NodeJS Support

Two sibling CometD subprojects provide respectively a https://github.com/cometd/cometd-nodejs-client/[client-side JavaScript library] and a https://github.com/cometd/cometd-nodejs-server/[server-side JavaScript library] for NodeJS.
Please refer to those sibling projects for further information if you need CometD to run in a NodeJS environment.

=== CometD Browser Support

In the documentation that follows, you will find information about the client-side JavaScript library to be used in browsers.

The CometD JavaScript library is a portable JavaScript implementation, entirely based on pure EcmaScript 6 and the standard objects available in the browser environment.
This implementation is what most applications should use.

[source,javascript]
----
import {CometD} from "cometd/cometd.js";

const cometd = new CometD();
----

CometD also provides _bindings_ for JavaScript toolkits, currently https://jquery.com/[jQuery].

This means that the CometD JavaScript implementation is written in pure JavaScript with no dependencies on the toolkits, and that the toolkit bindings add the syntactic sugar that makes the CometD APIs feel like they are native to the toolkit.
For example, it is possible to refer to a default `cometd` object when using jQuery, using the following notation:

[source,javascript]
----
// jQuery style.
import "jquery/jquery.cometd.js";

$.cometd.handshake();
----

The CometD APIs remain the same whether you use a binding or not, and the following sections do not refer to a particular binding.

The following sections present details about the JavaScript Bayeux APIs and their implementation secrets.

include::javascript_configure.adoc[]
include::javascript_handshake.adoc[]
include::javascript_subscribe.adoc[]
include::javascript_send.adoc[]
include::javascript_disconnect.adoc[]
include::javascript_batch.adoc[]
include::javascript_transports.adoc[]
